
influxdb:
  url: http://192.168.0.108:8086
  username: admin
  password: admin
  database: example
  batch:
    actions: 100
    flush-duration: 1000
    jitter-duration: 0
    buffer-limit: 10000
    precision: nanoseconds
    consistency: ONE
