version: '2.2'

services:
  tsdb:
    image: influxdb:latest
    volumes:
      - ./influxdb:/docker-entrypoint-initdb.d/:ro
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DB=example
      - INFLUXDB_HTTP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
#    restart: always